// Generated by CoffeeScript 1.12.7
var diConfiguration;

diConfiguration = (function() {
  function diConfiguration() {
    this.initTabs().initUploadedPics();
  }

  diConfiguration.prototype.initTabs = function() {
    new diTabs({
      $tabsContainer: $('.diadminform_tabs ul'),
      $pagesContainer: $('form [data-purpose="tab-pages"]')
    });
    $('form button[data-purpose="cancel"]').click(function() {
      if (confirm('All unsaved data will be lost. Are you sure?')) {
        window.location.reload();
      }
      return false;
    });
    $('.configuration form .grid .file-info a[data-purpose="del"]').on('click', function() {
      return confirm('Вы уверены?');
    });
    return this;
  };

  diConfiguration.prototype.initUploadedPics = function() {
    $('.configuration .grid .uploaded-pic img').on('click', function() {
      return $(this).parent().toggleClass('zoomed');
    });
    return this;
  };

  return diConfiguration;

})();

//# sourceMappingURL=diConfiguration.js.map
