// Generated by CoffeeScript 2.5.1
var FileDump;

FileDump = class FileDump {
  constructor(opts) {
    this.opts = $.extend({
      workerUri: null
    }, opts);
    this.setupCreateButton();
  }

  setupCreateButton() {
    $('[data-action="create.files"]').on('click', () => {
      this.log('Creating files dump...');
      $.post(this.opts.workerUri, {}, (res) => {
        if (res.ok) {
          return this.log('Files dump created');
        } else {
          return this.log('Error: ' + res.message);
        }
      });
      return false;
    });
    return this;
  }

  log(message) {
    A.console.add(message);
    return this;
  }

  error(message) {
    alert(message);
    return this;
  }

};

//# sourceMappingURL=FileDump.js.map
