// Generated by CoffeeScript 1.12.7
var LocalizationAdmin;

LocalizationAdmin = (function() {
  function LocalizationAdmin() {
    this.setupForm().setupList();
  }

  LocalizationAdmin.prototype.setupForm = function() {
    return this.setupAutoHeight();
  };

  LocalizationAdmin.prototype.setupList = function() {
    return this.setupExport();
  };

  LocalizationAdmin.prototype.setupAutoHeight = function() {
    setTimeout((function(_this) {
      return function() {
        return $('.diadminform-row').filter('[data-field$="value"]').find('textarea').autoHeight();
      };
    })(this), 100);
    return this;
  };

  LocalizationAdmin.prototype.setupExport = function() {
    $('.filter-block [name="export"]').on('click', function() {
      var $cb, $out, $t, linesAr, names;
      $t = $('.dinicetable');
      $cb = $t.find('tr td.id .checked, tr td.id input:checkbox:checked');
      linesAr = [];
      names = [];
      $out = $('.export-block');
      if ($out.length && $out.is(':visible')) {
        $out.hide();
        return false;
      }
      if (!$cb.length) {
        alert('Выберите хотя бы один Токен');
        return false;
      }
      $cb.each(function() {
        var $td, s, val, valuesAr;
        valuesAr = [];
        $td = $(this).parent();
        while ($td = $td.next('td:eq(0)')) {
          if ($td.hasClass('btn')) {
            break;
          }
          val = $td.find('[data-purpose="orig"]').html();
          if (val === void 0 || val === null) {
            val = $td.html();
          }
          val = val.replace(/'/g, '\\\'').replace(/"/g, '\\\"');
          if ($td.data('field') === 'name') {
            names.push(val);
          }
          valuesAr.push(val);
        }
        s = '$this->getDb()->q("INSERT IGNORE INTO `' + $t.data('table') + '`(`name`,`value`,`en_value`,`de_value`,`it_value`,`es_value`,`fr_value`)\n' + '\u0009\u0009\u0009VALUES(\'' + valuesAr.join('\',\'') + '\');' + '");';
        linesAr.push(s);
        return true;
      });
      if (!$out.length) {
        $out = $('<div class="export-block"><textarea></textarea></div>').insertAfter($(this).parent());
      }
      $out.show().find('textarea').val(names.map((function(_this) {
        return function(n) {
          return "'" + n + "',";
        };
      })(this)).concat(linesAr).join('\n'));
      return false;
    });
    return this;
  };

  return LocalizationAdmin;

})();

//# sourceMappingURL=LocalizationAdmin.js.map
