// Generated by CoffeeScript 1.10.0
var LocalizationAdmin;

LocalizationAdmin = (function() {
  function LocalizationAdmin() {
    this.setupForm().setupList();
  }

  LocalizationAdmin.prototype.setupForm = function() {
    return this.setupAutoHeight();
  };

  LocalizationAdmin.prototype.setupList = function() {
    return this.setupExport();
  };

  LocalizationAdmin.prototype.setupAutoHeight = function() {
    $('.diadminform-row').filter('[data-field$="value"]').find('textarea').autoHeight();
    return this;
  };

  LocalizationAdmin.prototype.setupExport = function() {
    $('.filter-block [name="export"]').on('click', function() {
      var $cb, $out, $t, linesAr;
      $t = $('.dinicetable');
      $cb = $t.find('tr td.id .checked, tr td.id input:checkbox:checked');
      linesAr = [];
      $out = $('.export-block');
      if ($out.length && $out.is(':visible')) {
        $out.hide();
        return false;
      }
      if (!$cb.length) {
        alert('Выберите хотя бы один Токен');
        return false;
      }
      $cb.each(function() {
        var $td, s, val, valuesAr;
        valuesAr = [];
        $td = $(this).parent();
        while ($td = $td.next('td:eq(0)')) {
          if ($td.hasClass('btn')) {
            break;
          }
          val = $td.find('[data-purpose="orig"]').html();
          if (val === void 0 || val === null) {
            val = $td.html();
          }
          valuesAr.push(val).replace(/'/g, '\\\'').replace(/"/g, '\"');
        }
        s = '$this->getDb()->q("INSERT IGNORE INTO `' + $t.data('table') + '`(`name`,`value`,`en_value`,`de_value`,`it_value`,`es_value`,`fr_value`)\n' + '\u0009\u0009\u0009VALUES(\'' + valuesAr.join('\',\'') + '\');' + '");';
        linesAr.push(s);
        return true;
      });
      if (!$out.length) {
        $out = $('<div class="export-block"><textarea></textarea></div>').insertAfter($(this).parent());
      }
      $out.show().find('textarea').val(linesAr.join('\n'));
      return false;
    });
    return this;
  };

  return LocalizationAdmin;

})();

//# sourceMappingURL=LocalizationAdmin.js.map
