<?php
/**
 * Created by diModelsManager
 * Date: 27.06.2016
 * Time: 17:33
 */

/**
 * Class diVideoCollection
 * Methods list for IDE
 *
 * @method diVideoCollection filterById($value, $operator = null)
 * @method diVideoCollection filterByAlbumId($value, $operator = null)
 * @method diVideoCollection filterByVendor($value, $operator = null)
 * @method diVideoCollection filterByVendorVideoUid($value, $operator = null)
 * @method diVideoCollection filterBySlug($value, $operator = null)
 * @method diVideoCollection filterBySlugSource($value, $operator = null)
 * @method diVideoCollection filterBySeasonId($value, $operator = null)
 * @method diVideoCollection filterByTitle($value, $operator = null)
 * @method diVideoCollection filterByContent($value, $operator = null)
 * @method diVideoCollection filterByEmbed($value, $operator = null)
 * @method diVideoCollection filterByVideoMp4($value, $operator = null)
 * @method diVideoCollection filterByVideoM4v($value, $operator = null)
 * @method diVideoCollection filterByVideoOgv($value, $operator = null)
 * @method diVideoCollection filterByVideoWebm($value, $operator = null)
 * @method diVideoCollection filterByVideoW($value, $operator = null)
 * @method diVideoCollection filterByVideoH($value, $operator = null)
 * @method diVideoCollection filterByPic($value, $operator = null)
 * @method diVideoCollection filterByPicW($value, $operator = null)
 * @method diVideoCollection filterByPicH($value, $operator = null)
 * @method diVideoCollection filterByPicT($value, $operator = null)
 * @method diVideoCollection filterByPicTnW($value, $operator = null)
 * @method diVideoCollection filterByPicTnH($value, $operator = null)
 * @method diVideoCollection filterByViewsCount($value, $operator = null)
 * @method diVideoCollection filterByDate($value, $operator = null)
 * @method diVideoCollection filterByOrderNum($value, $operator = null)
 * @method diVideoCollection filterByVisible($value, $operator = null)
 * @method diVideoCollection filterByTop($value, $operator = null)
 * @method diVideoCollection filterByCommentsEnabled($value, $operator = null)
 * @method diVideoCollection filterByCommentsLastDate($value, $operator = null)
 * @method diVideoCollection filterByCommentsCount($value, $operator = null)
 *
 * @method diVideoCollection orderById($direction = null)
 * @method diVideoCollection orderByAlbumId($direction = null)
 * @method diVideoCollection orderByVendor($direction = null)
 * @method diVideoCollection orderByVendorVideoUid($direction = null)
 * @method diVideoCollection orderBySlug($direction = null)
 * @method diVideoCollection orderBySlugSource($direction = null)
 * @method diVideoCollection orderBySeasonId($direction = null)
 * @method diVideoCollection orderByTitle($direction = null)
 * @method diVideoCollection orderByContent($direction = null)
 * @method diVideoCollection orderByEmbed($direction = null)
 * @method diVideoCollection orderByVideoMp4($direction = null)
 * @method diVideoCollection orderByVideoM4v($direction = null)
 * @method diVideoCollection orderByVideoOgv($direction = null)
 * @method diVideoCollection orderByVideoWebm($direction = null)
 * @method diVideoCollection orderByVideoW($direction = null)
 * @method diVideoCollection orderByVideoH($direction = null)
 * @method diVideoCollection orderByPic($direction = null)
 * @method diVideoCollection orderByPicW($direction = null)
 * @method diVideoCollection orderByPicH($direction = null)
 * @method diVideoCollection orderByPicT($direction = null)
 * @method diVideoCollection orderByPicTnW($direction = null)
 * @method diVideoCollection orderByPicTnH($direction = null)
 * @method diVideoCollection orderByViewsCount($direction = null)
 * @method diVideoCollection orderByDate($direction = null)
 * @method diVideoCollection orderByOrderNum($direction = null)
 * @method diVideoCollection orderByVisible($direction = null)
 * @method diVideoCollection orderByTop($direction = null)
 * @method diVideoCollection orderByCommentsEnabled($direction = null)
 * @method diVideoCollection orderByCommentsLastDate($direction = null)
 * @method diVideoCollection orderByCommentsCount($direction = null)
 *
 * @method diVideoCollection selectId()
 * @method diVideoCollection selectAlbumId()
 * @method diVideoCollection selectVendor()
 * @method diVideoCollection selectVendorVideoUid()
 * @method diVideoCollection selectSlug()
 * @method diVideoCollection selectSlugSource()
 * @method diVideoCollection selectSeasonId()
 * @method diVideoCollection selectTitle()
 * @method diVideoCollection selectContent()
 * @method diVideoCollection selectEmbed()
 * @method diVideoCollection selectVideoMp4()
 * @method diVideoCollection selectVideoM4v()
 * @method diVideoCollection selectVideoOgv()
 * @method diVideoCollection selectVideoWebm()
 * @method diVideoCollection selectVideoW()
 * @method diVideoCollection selectVideoH()
 * @method diVideoCollection selectPic()
 * @method diVideoCollection selectPicW()
 * @method diVideoCollection selectPicH()
 * @method diVideoCollection selectPicT()
 * @method diVideoCollection selectPicTnW()
 * @method diVideoCollection selectPicTnH()
 * @method diVideoCollection selectViewsCount()
 * @method diVideoCollection selectDate()
 * @method diVideoCollection selectOrderNum()
 * @method diVideoCollection selectVisible()
 * @method diVideoCollection selectTop()
 * @method diVideoCollection selectCommentsEnabled()
 * @method diVideoCollection selectCommentsLastDate()
 * @method diVideoCollection selectCommentsCount()
 */
class diVideoCollection extends diCollection
{
	const type = diTypes::video;
	protected $table = "videos";
	protected $modelType = "video";
}