CREATE TABLE IF NOT EXISTS admin_table_edit_log(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_table text,
    target_id    bigint,
    admin_id     int,
    old_data     text,
    new_data     text,
    operation    text        not null default 'update',
    created_at   timestamptz default CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx__admin_table_edit_log
    ON admin_table_edit_log (target_table, target_id, admin_id, created_at);
