CREATE TABLE IF NOT EXISTS admins(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login text,
  password text,
  first_name text,
  last_name text,
  email text,
  phone text,
  address text default '',
  date timestamptz default CURRENT_TIMESTAMP,
  ip bigint,
  host text,
  level text,
  active smallint default '1'
);

CREATE INDEX IF NOT EXISTS idx__admins
ON admins (login,email,active);
