CREATE TABLE IF NOT EXISTS ads
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id           INT,
    category_id        INT         DEFAULT '0',
    title              text,
    content            TEXT,
    href               text,
    href_target        smallint    DEFAULT '0',
    properties         jsonb,
    onclick            text        DEFAULT '',
    button_color       text        DEFAULT '',
    transition         smallint    DEFAULT '0',
    transition_style   smallint    DEFAULT '0',
    duration_of_show   INT         DEFAULT '-1',
    duration_of_change INT         DEFAULT '-1',
    pic                text        DEFAULT '',
    pic_w              INT         DEFAULT '0',
    pic_h              INT         DEFAULT '0',
    visible            smallint    DEFAULT '1',
    order_num          INT,
    date               timestamptz DEFAULT CURRENT_TIMESTAMP,
    show_date1         DATE        NULL    DEFAULT NULL,
    show_date2         DATE        NULL    DEFAULT NULL,
    show_time1         TIME        NULL    DEFAULT NULL,
    show_time2         TIME        NULL    DEFAULT NULL,
    show_on_weekdays   text        DEFAULT '',
    show_on_holidays   smallint    DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx__ads
    ON ads (block_id, category_id, show_date1, show_date2, show_time1, show_time2, show_on_weekdays, show_on_holidays,
            visible, order_num);
