CREATE TABLE IF NOT EXISTS dipics
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    _table     text        default '',
    _field     text        default '',
    _id        bigint,
    target_id  bigint      default '0',
    title      text,
    content    text,
    orig_fn    text        default '',
    pic        text,
    pic_t      int         default '0',
    pic_w      int,
    pic_h      int,
    pic_tn     text        default '',
    pic_tn_t   int         default '0',
    pic_tn_w   int,
    pic_tn_h   int,
    pic_tn2_t  int         default '0',
    pic_tn2_w  int,
    pic_tn2_h  int,
    date       timestamptz default CURRENT_TIMESTAMP,
    by_default smallint    default '0',
    visible    smallint    default '1',
    order_num  bigint
);

CREATE INDEX IF NOT EXISTS idx__dipics__main
    ON dipics (_table, _id, _field, by_default);

CREATE INDEX IF NOT EXISTS idx__dipics__visible
    ON dipics (visible, order_num, date, _table, _field, _id);
