CREATE TABLE IF NOT EXISTS news
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clean_title        text,
    menu_title         text        default '',
    title              text,
    short_content      text,
    content            text,
    html_title         text        default '',
    html_keywords      text        default '',
    html_description   text        default '',
    pic                text        default '',
    pic_w              int         default '0',
    pic_h              int         default '0',
    pic_t              int         default '0',
    pic_tn_w           int         default '0',
    pic_tn_h           int         default '0',
    date               timestamptz,
    visible            smallint    default '1',
    order_num          bigint,
    karma              int         default '0',
    comments_count     int         default '0',
    comments_last_date timestamptz default NULL,
    comments_enabled   smallint    default '1'
);

CREATE INDEX IF NOT EXISTS idx__news
    ON news (visible, order_num, date);

CREATE UNIQUE INDEX IF NOT EXISTS idx__news__clean_title
    ON news (clean_title);
