CREATE TABLE IF NOT EXISTS dipics(
  id bigint not null auto_increment,
  _table varchar(100) default '',
  _field varchar(100) default '',
  _id bigint,
  target_id bigint default '0',
  title varchar(255),
  content text,
  orig_fn varchar(100) default '',
  pic varchar(50),
  pic_t int default '0',
  pic_w int,
  pic_h int,
  pic_tn varchar(50) default '',
  pic_tn_t int default '0',
  pic_tn_w int,
  pic_tn_h int,
  pic_tn2_t int default '0',
  pic_tn2_w int,
  pic_tn2_h int,
  date timestamp default CURRENT_TIMESTAMP,
  by_default tinyint default '0',
  visible tinyint default '1',
  order_num bigint,
  index visible_idx(visible,order_num,date,_table,_field,_id),
  index idx2(_table,_id,_field,by_default),
  primary key(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
