<?php
/**
 * Created by PhpStorm.
 * User: dimaninc
 * Date: 21.03.2017
 * Time: 21:48
 */

namespace diCore\Entity\Content;

/**
 * Class Collection
 * Methods list for IDE
 *
 * @method Collection filterById($value, $operator = null)
 * @method Collection filterByParent($value, $operator = null)
 * @method Collection filterByCleanTitle($value, $operator = null)
 * @method Collection filterByMenuTitle($value, $operator = null)
 * @method Collection filterByType($value, $operator = null)
 * @method Collection filterByTitle($value, $operator = null)
 * @method Collection filterByCaption($value, $operator = null)
 * @method Collection filterByHtmlTitle($value, $operator = null)
 * @method Collection filterByHtmlKeywords($value, $operator = null)
 * @method Collection filterByHtmlDescription($value, $operator = null)
 * @method Collection filterByContent($value, $operator = null)
 * @method Collection filterByShortContent($value, $operator = null)
 * @method Collection filterByLinksContent($value, $operator = null)
 * @method Collection filterByPic($value, $operator = null)
 * @method Collection filterByPicW($value, $operator = null)
 * @method Collection filterByPicH($value, $operator = null)
 * @method Collection filterByPicT($value, $operator = null)
 * @method Collection filterByPic2($value, $operator = null)
 * @method Collection filterByPic2W($value, $operator = null)
 * @method Collection filterByPic2H($value, $operator = null)
 * @method Collection filterByPic2T($value, $operator = null)
 * @method Collection filterByIco($value, $operator = null)
 * @method Collection filterByIcoW($value, $operator = null)
 * @method Collection filterByIcoH($value, $operator = null)
 * @method Collection filterByIcoT($value, $operator = null)
 * @method Collection filterByColor($value, $operator = null)
 * @method Collection filterByBackgroundColor($value, $operator = null)
 * @method Collection filterByClass($value, $operator = null)
 * @method Collection filterByMenuClass($value, $operator = null)
 * @method Collection filterByLevelNum($value, $operator = null)
 * @method Collection filterByVisible($value, $operator = null)
 * @method Collection filterByVisibleTop($value, $operator = null)
 * @method Collection filterByVisibleBottom($value, $operator = null)
 * @method Collection filterByVisibleLeft($value, $operator = null)
 * @method Collection filterByVisibleRight($value, $operator = null)
 * @method Collection filterByVisibleLoggedIn($value, $operator = null)
 * @method Collection filterByToShowContent($value, $operator = null)
 * @method Collection filterByOrderNum($value, $operator = null)
 * @method Collection filterByTop($value, $operator = null)
 * @method Collection filterByCreatedAt($value, $operator = null)
 * @method Collection filterByUpdatedAt($value, $operator = null)
 * @method Collection filterByCommentsCount($value, $operator = null)
 * @method Collection filterByCommentsLastDate($value, $operator = null)
 * @method Collection filterByCommentsEnabled($value, $operator = null)
 * @method Collection filterByAdBlockId($value, $operator = null)
 *
 * @method Collection orderById($direction = null)
 * @method Collection orderByParent($direction = null)
 * @method Collection orderByCleanTitle($direction = null)
 * @method Collection orderByMenuTitle($direction = null)
 * @method Collection orderByType($direction = null)
 * @method Collection orderByTitle($direction = null)
 * @method Collection orderByCaption($direction = null)
 * @method Collection orderByHtmlTitle($direction = null)
 * @method Collection orderByHtmlKeywords($direction = null)
 * @method Collection orderByHtmlDescription($direction = null)
 * @method Collection orderByContent($direction = null)
 * @method Collection orderByShortContent($direction = null)
 * @method Collection orderByLinksContent($direction = null)
 * @method Collection orderByPic($direction = null)
 * @method Collection orderByPicW($direction = null)
 * @method Collection orderByPicH($direction = null)
 * @method Collection orderByPicT($direction = null)
 * @method Collection orderByPic2($direction = null)
 * @method Collection orderByPic2W($direction = null)
 * @method Collection orderByPic2H($direction = null)
 * @method Collection orderByPic2T($direction = null)
 * @method Collection orderByIco($direction = null)
 * @method Collection orderByIcoW($direction = null)
 * @method Collection orderByIcoH($direction = null)
 * @method Collection orderByIcoT($direction = null)
 * @method Collection orderByColor($direction = null)
 * @method Collection orderByBackgroundColor($direction = null)
 * @method Collection orderByClass($direction = null)
 * @method Collection orderByMenuClass($direction = null)
 * @method Collection orderByLevelNum($direction = null)
 * @method Collection orderByVisible($direction = null)
 * @method Collection orderByVisibleTop($direction = null)
 * @method Collection orderByVisibleBottom($direction = null)
 * @method Collection orderByVisibleLeft($direction = null)
 * @method Collection orderByVisibleRight($direction = null)
 * @method Collection orderByVisibleLoggedIn($direction = null)
 * @method Collection orderByToShowContent($direction = null)
 * @method Collection orderByOrderNum($direction = null)
 * @method Collection orderByTop($direction = null)
 * @method Collection orderByCreatedAt($direction = null)
 * @method Collection orderByUpdatedAt($direction = null)
 * @method Collection orderByCommentsCount($direction = null)
 * @method Collection orderByCommentsLastDate($direction = null)
 * @method Collection orderByCommentsEnabled($direction = null)
 * @method Collection orderByAdBlockId($direction = null)
 *
 * @method Collection selectId()
 * @method Collection selectParent()
 * @method Collection selectCleanTitle()
 * @method Collection selectMenuTitle()
 * @method Collection selectType()
 * @method Collection selectTitle()
 * @method Collection selectCaption()
 * @method Collection selectHtmlTitle()
 * @method Collection selectHtmlKeywords()
 * @method Collection selectHtmlDescription()
 * @method Collection selectContent()
 * @method Collection selectShortContent()
 * @method Collection selectLinksContent()
 * @method Collection selectPic()
 * @method Collection selectPicW()
 * @method Collection selectPicH()
 * @method Collection selectPicT()
 * @method Collection selectPic2()
 * @method Collection selectPic2W()
 * @method Collection selectPic2H()
 * @method Collection selectPic2T()
 * @method Collection selectIco()
 * @method Collection selectIcoW()
 * @method Collection selectIcoH()
 * @method Collection selectIcoT()
 * @method Collection selectColor()
 * @method Collection selectBackgroundColor()
 * @method Collection selectClass()
 * @method Collection selectMenuClass()
 * @method Collection selectLevelNum()
 * @method Collection selectVisible()
 * @method Collection selectVisibleTop()
 * @method Collection selectVisibleBottom()
 * @method Collection selectVisibleLeft()
 * @method Collection selectVisibleRight()
 * @method Collection selectVisibleLoggedIn()
 * @method Collection selectToShowContent()
 * @method Collection selectOrderNum()
 * @method Collection selectTop()
 * @method Collection selectCreatedAt()
 * @method Collection selectUpdatedAt()
 * @method Collection selectCommentsCount()
 * @method Collection selectCommentsLastDate()
 * @method Collection selectCommentsEnabled()
 * @method Collection selectAdBlockId()
 */
class Collection extends \diCollection
{
	const type = \diTypes::content;
	protected $table = 'content';
	protected $modelType = 'content';
}